load("@rules_java//java:defs.bzl", "java_binary")

package(default_visibility = ["//visibility:public"])

java_binary(
    name = "trapping_rain_water_ii",
    srcs = glob(["*.java"]),
    main_class = "silviobraendle.trapping_rain_water_ii.Main",
    deps = [
    ],
)
