load("@rules_java//java:defs.bzl", "java_binary")

package(default_visibility = ["//visibility:public"])

java_binary(
    name = "n1",
    main_class = "cediackermann.n1.Main",
    srcs = glob(["*.java"]),
    deps = [
    ],
)
