load("@rules_java//java:defs.bzl", "java_binary")

package(default_visibility = ["//visibility:public"])

java_binary(
    name = "houseRobber",
    main_class = "cediackermann.challenges.houseRobber.Main",
    srcs = glob(["*.java"]),
    deps = [
    ],
)
