load("@rules_java//java:defs.bzl", "java_binary")

package(default_visibility = ["//visibility:public"])

java_binary(
    name = "two_sum",
    srcs = glob(["*.java"]),
    main_class = "silviobraendle.two_sum.Main",
    deps = [
    ],
)
